### ISSUE TITLE
Callbacks tracker

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/Xpress.jl#5]
Main tracker for callbacks:

- [ ] Map main JuMP/MathProgBase related callback functions
- [ ] Choose the ones to be implemented
- [ ] Implement Low-level calls (plain C-wrapper)
- [ ] Add to SolverInterface and make it work with MathProgBase
